# Site settings
title: Van Hien Tran
email: tran.vanhien at nict.go.jp
description: # this means to ignore newlines until "baseurl:"
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vhientran.github.io" # the base hostname & protocol for your site

google_scholar_id: Pi48KT8AAAAJ
github_username:  vhientran

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Postdoctoral Researcher"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
